#!/usr/bin/env python3
"""Structural validator for employee packs generated by universal-ai-employee-builder."""

from __future__ import annotations

import json
import sys
from pathlib import Path

REQUIRED_FILES = [
    "EMPLOYEE.md",
    "employee-contract.yaml",
    "authority-matrix.yaml",
    "tool-map.yaml",
    "memory-policy.md",
    "runtime-adapter.md",
    "task-ledger.schema.json",
    "evals/eval-cases.yaml",
]


def fail(msg: str) -> None:
    print(f"FAIL: {msg}")


def main() -> int:
    if len(sys.argv) != 2:
        print("Usage: validate_employee_pack.py <employee-directory>")
        return 2

    root = Path(sys.argv[1]).expanduser().resolve()
    if not root.is_dir():
        fail(f"not a directory: {root}")
        return 1

    errors = 0
    for rel in REQUIRED_FILES:
        p = root / rel
        if not p.is_file():
            fail(f"missing required file: {rel}")
            errors += 1
        elif p.stat().st_size == 0:
            fail(f"empty required file: {rel}")
            errors += 1

    schema_path = root / "task-ledger.schema.json"
    if schema_path.is_file():
        try:
            json.loads(schema_path.read_text(encoding="utf-8"))
        except Exception as exc:
            fail(f"task-ledger.schema.json is not valid JSON: {exc}")
            errors += 1

    employee_md = root / "EMPLOYEE.md"
    if employee_md.is_file():
        text = employee_md.read_text(encoding="utf-8", errors="replace").lower()
        for marker in ["mission", "authority", "verification", "escalation"]:
            if marker not in text:
                fail(f"EMPLOYEE.md does not mention expected concept: {marker}")
                errors += 1

    if errors:
        print(f"\n{errors} structural problem(s) found.")
        return 1

    print("PASS: employee pack has the required structure and valid ledger JSON schema.")
    print("Note: structural validation does not prove safety, authorization, or task quality.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
